// <auto-generated />
namespace ImsForPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_ProductImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ProductImage));
        
        string IMigrationMetadata.Id
        {
            get { return "201604202031540_add_ProductImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
